// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartExpenseTracker.API.Data;

#nullable disable

namespace SmartExpenseTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324212901_AddedRecieptScanner")]
    partial class AddedRecieptScanner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Amount = 50.0,
                            Category = "Food",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groceries from Walmart"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber ride to downtown"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 15.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly Netflix subscription"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor's appointment fee"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1000.0,
                            Category = "Education",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "College tuition payment"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 120.0,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 70.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothes from Zara"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 300.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flight to Toronto"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 4.5,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee at Starbucks"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 12.75,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lunch at McDonald's"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 67.900001525878906,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grocery shopping at Walmart"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 18.25,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber ride downtown"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 45.299999237060547,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas refill"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 10.5,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Train ticket"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 15.989999771118164,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix subscription"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 14.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Movie ticket"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 75.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concert ticket"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 120.44999694824219,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 65.989997863769531,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Internet bill"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 35.200000762939453,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water bill"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 120.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amazon purchase - headphones"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 45.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing from H&M"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 90.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shoes from Nike"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 150.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor's visit"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 30.25,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pharmacy - medication"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 200.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dental checkup"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 45.0,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Online course on Udemy"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 120.0,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Textbooks"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 25.5,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "School supplies"
                        },
                        new
                        {
                            Id = 31,
                            Amount = 350.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flight ticket"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 120.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hotel booking"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 85.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car rental"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 250.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Health insurance"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 180.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car insurance"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 300.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home insurance"
                        },
                        new
                        {
                            Id = 37,
                            Amount = 40.0,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Birthday gift"
                        },
                        new
                        {
                            Id = 38,
                            Amount = 20.0,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Donation"
                        },
                        new
                        {
                            Id = 39,
                            Amount = 5.5,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Postage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
