// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartExpenseTracker.API.Data;

#nullable disable

namespace SmartExpenseTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250323175614_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Amount = 50m,
                            Category = "Food",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Groceries from Walmart"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20m,
                            Category = "Transportation",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Uber ride to downtown"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 15m,
                            Category = "Entertainment",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Monthly Netflix subscription"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100m,
                            Category = "Healthcare",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Doctor's appointment fee"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1000m,
                            Category = "Education",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "College tuition payment"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 120m,
                            Category = "Utilities",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Electricity bill"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 70m,
                            Category = "Shopping",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Clothes from Zara"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 300m,
                            Category = "Travel",
                            Date = new DateTime(2025, 3, 23, 17, 48, 37, 0, DateTimeKind.Utc),
                            Description = "Flight to Toronto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
