// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartExpenseTracker.API.Data;

#nullable disable

namespace SmartExpenseTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartExpenseTracker.API.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartExpenseTracker.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Amount = 50.0,
                            Category = "Food",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groceries from Walmart"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber ride to downtown"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 15.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly Netflix subscription"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor's appointment fee"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1000.0,
                            Category = "Education",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "College tuition payment"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 120.0,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 70.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothes from Zara"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 300.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flight to Toronto"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 4.5,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee at Starbucks"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 12.75,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lunch at McDonald's"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 67.900001525878906,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grocery shopping at Walmart"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 18.25,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber ride downtown"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 45.299999237060547,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas refill"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 10.5,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Train ticket"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 15.989999771118164,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix subscription"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 14.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Movie ticket"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 75.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concert ticket"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 120.44999694824219,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 65.989997863769531,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Internet bill"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 35.200000762939453,
                            Category = "Utilities",
                            Date = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water bill"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 120.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amazon purchase - headphones"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 45.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing from H&M"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 90.0,
                            Category = "Shopping",
                            Date = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shoes from Nike"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 150.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor's visit"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 30.25,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pharmacy - medication"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 200.0,
                            Category = "Healthcare",
                            Date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dental checkup"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 45.0,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Online course on Udemy"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 120.0,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Textbooks"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 25.5,
                            Category = "Education",
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "School supplies"
                        },
                        new
                        {
                            Id = 31,
                            Amount = 350.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flight ticket"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 120.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hotel booking"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 85.0,
                            Category = "Travel",
                            Date = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car rental"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 250.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Health insurance"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 180.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car insurance"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 300.0,
                            Category = "Insurance",
                            Date = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home insurance"
                        },
                        new
                        {
                            Id = 37,
                            Amount = 40.0,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Birthday gift"
                        },
                        new
                        {
                            Id = 38,
                            Amount = 20.0,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Donation"
                        },
                        new
                        {
                            Id = 39,
                            Amount = 5.5,
                            Category = "Miscellaneous",
                            Date = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Postage"
                        },
                        new
                        {
                            Id = 100,
                            Amount = 3.5,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee at Tim Hortons"
                        },
                        new
                        {
                            Id = 101,
                            Amount = 8.9899997711181641,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lunch at Subway"
                        },
                        new
                        {
                            Id = 102,
                            Amount = 14.5,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dinner at KFC"
                        },
                        new
                        {
                            Id = 103,
                            Amount = 120.75,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grocery shopping at T&T Supermarket"
                        },
                        new
                        {
                            Id = 104,
                            Amount = 5.0,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Snack at 7-Eleven"
                        },
                        new
                        {
                            Id = 105,
                            Amount = 9.25,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Burger King meal"
                        },
                        new
                        {
                            Id = 106,
                            Amount = 78.199996948242188,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grocery shopping at Walmart"
                        },
                        new
                        {
                            Id = 107,
                            Amount = 2.75,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee at McDonald's"
                        },
                        new
                        {
                            Id = 108,
                            Amount = 4.9899997711181641,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ice cream at Dairy Queen"
                        },
                        new
                        {
                            Id = 109,
                            Amount = 18.450000762939453,
                            Category = "Food & Dining",
                            Date = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pizza at Domino's"
                        },
                        new
                        {
                            Id = 110,
                            Amount = 3.25,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bus fare"
                        },
                        new
                        {
                            Id = 111,
                            Amount = 45.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taxi ride to airport"
                        },
                        new
                        {
                            Id = 112,
                            Amount = 55.400001525878906,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas refill at Shell"
                        },
                        new
                        {
                            Id = 113,
                            Amount = 320.75,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flight to Toronto"
                        },
                        new
                        {
                            Id = 114,
                            Amount = 20.5,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber ride to downtown"
                        },
                        new
                        {
                            Id = 115,
                            Amount = 12.5,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Train ticket"
                        },
                        new
                        {
                            Id = 116,
                            Amount = 5.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric scooter rental"
                        },
                        new
                        {
                            Id = 117,
                            Amount = 10.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parking fee"
                        },
                        new
                        {
                            Id = 118,
                            Amount = 15.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Car wash"
                        },
                        new
                        {
                            Id = 119,
                            Amount = 60.0,
                            Category = "Transportation",
                            Date = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oil change"
                        },
                        new
                        {
                            Id = 120,
                            Amount = 15.989999771118164,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix subscription"
                        },
                        new
                        {
                            Id = 121,
                            Amount = 13.5,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Movie at Cineplex"
                        },
                        new
                        {
                            Id = 122,
                            Amount = 12.989999771118164,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spotify premium"
                        },
                        new
                        {
                            Id = 123,
                            Amount = 80.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concert ticket"
                        },
                        new
                        {
                            Id = 124,
                            Amount = 9.9899997711181641,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming subscription"
                        },
                        new
                        {
                            Id = 125,
                            Amount = 28.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Escape room"
                        },
                        new
                        {
                            Id = 126,
                            Amount = 20.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bowling night"
                        },
                        new
                        {
                            Id = 127,
                            Amount = 15.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Karaoke night"
                        },
                        new
                        {
                            Id = 128,
                            Amount = 18.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Museum entry"
                        },
                        new
                        {
                            Id = 129,
                            Amount = 25.0,
                            Category = "Entertainment",
                            Date = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comedy show"
                        },
                        new
                        {
                            Id = 130,
                            Amount = 100.25,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric bill"
                        },
                        new
                        {
                            Id = 131,
                            Amount = 60.75,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Internet bill"
                        },
                        new
                        {
                            Id = 132,
                            Amount = 40.0,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water bill"
                        },
                        new
                        {
                            Id = 133,
                            Amount = 70.5,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heating bill"
                        },
                        new
                        {
                            Id = 134,
                            Amount = 55.0,
                            Category = "Utilities",
                            Date = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phone bill"
                        },
                        new
                        {
                            Id = 135,
                            Amount = 45.0,
                            Category = "Health & Fitness",
                            Date = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gym membership"
                        },
                        new
                        {
                            Id = 136,
                            Amount = 70.0,
                            Category = "Health & Fitness",
                            Date = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Massage therapy"
                        },
                        new
                        {
                            Id = 137,
                            Amount = 15.0,
                            Category = "Health & Fitness",
                            Date = new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yoga class"
                        },
                        new
                        {
                            Id = 138,
                            Amount = 90.0,
                            Category = "Health & Fitness",
                            Date = new DateTime(2023, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Personal trainer"
                        },
                        new
                        {
                            Id = 139,
                            Amount = 35.0,
                            Category = "Health & Fitness",
                            Date = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supplements"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartExpenseTracker.API.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartExpenseTracker.API.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartExpenseTracker.API.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartExpenseTracker.API.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
